### ISSUE TITLE
offline file saving

### ISSUE THREAD

**Issue by tnguyen10** [CMPUT301F18T20/MedicalPhotoRecord#102]

**Comment by modelarious** [comment]
We need a "date last modified field" on any object that will be edit-able offline.  That way we know if two edits happen to a file, one online and one offline, which one is more recent and should be the master in the database.

**Comment by tnguyen10** [comment]
About how this, I was wondering if we could always just trust the offline database to be the most recent one? Since online database can switch off, but offline database will probably "never" crashes.

And once we are back online, we just have to rewrite whatever from the offline to the online database

**Comment by modelarious** [comment]
Are you thinking that we update the offline database from the online database and display data from the offline one?

**Comment by tnguyen10** [comment]
Uhm... I'm thinking that we should rely on offline database as our main database since elastic search can be down dues to wifi problem. We'll update both offline and elastic search (when there's wifi), but when there's not we'll continue using offline database (since it is not affected). 

If wifi is back on again, we'll update elastic search database with our offline one

I'm suggesting this because I think our most reliable database will be the offline one since I don't think there's anything that would cause it to fail?

**Comment by modelarious** [comment]
I agree that when there is no wifi that we should use what we have stored offline and I think we should use the offline storage for display from all activities, but the online/offline sync issue has a few subtleties if we can have more than one device logged into the same account.

The Provider will only be reading from the database except for when they write a "Record" or their own contact information, so they don't touch any Patient data directly (though the Record object will reference the id of a Patient's Problem).  The Patient will read and write their contact info, problems and patient records.  If we restrict the Patient to only being able to be logged in for one session (including offline sessions) then the proposed method will work as no data could be edited by a two users at once, but a patient could technically be logged in online on one phone, offline logged in on another.  From the offline phone they change the name of their problem "A" to "C", from the online phone they change the name of problem "A" to "B". What would happen when the offline phone comes online?

Do we need to worry about this kind of thing or can we assume we don't have to handle multiple devices logged into the same account editing related entries?

Is there any way to restrict how many devices are logged into an account anyways? Infinite could be logged in offline unless we require sign in to happen online and enforce that only one session can be active at a time by requiring the logged in session to sign out before another device can sign into the account.  This would be really bad<sup>TM</sup>

**Comment by tnguyen10** [comment]
Yes, that's true, I think that's one of the reason why they asked us to do an online database (elastic search). 

We need to keep track of changes made in offline that are not synced to online (when wifi is down) and changes made over online database that are not synced to offline (multiple devices or if someone/ prof/ ta access and changes our elastic search database). I don't think we could restrict the number of devices logged in that can access our database, we should assume that our online database is always changing just to be safe.

You were right in suggesting that we should keep a last modified date on each of our informations, so that every time the app needs to display information, it would have to fetch from both databases, compare each entry's last modified date and take the one the was last updated. Then it could rewrite  those entries back to both databases.

**Comment by modelarious** [comment]
Yeah, that should work well. I like the idea of rewriting the info back to both databases. We'll need to make sure that we store the ids in both the offline and online databases so we can be comparing the same object when we do the comparisons.

**Comment by modelarious** [comment]
Requirement for this segment: As soon as a user's device is back online, it needs to upload all of the offline changes it has made to the elastic search.

Do we want to do a prefetch as soon as the user logs in?  Get a copy of their records, problems, patient records and contact info of their providers?  That way if they go offline, they have data to work with?

**Comment by modelarious** [comment]
I think it would make sense to have a metadata database, in which each entry holds only the id of the object it is tracking and the last modified date.  Using records as an example: When we want to find out which of our offline records are out of date, we query the metadata database with the record ids we have and then compare the date modified fields.  We determine which offline records are out of date and query only those records from the record database to replace the ones we have.

The advantage is that less data is fetched as we only fetch the records that are out of date instead of all the associated records.

**Comment by tnguyen10** [comment]
yes, I think we'll probably have prefetch the online data that's been changed for the 2 database to be consistent

For the metadata database, 
it'll have to holds both the records' infos that's been changed from online database, these then are fetched to update the offline database
it'll also have to hold records's infos that's been changed from offline too (when there's no wifi), these then are pushed to online database ?

**Comment by modelarious** [comment]
If you had a Record in the database:
```
Record{
    "AssociatedUserDatabaseID" : "LETTERSANDNUMBERS"
    "AssociatedProblemID" : "NUMBERSANDLETTERS"
    "RecordID" : "LettersAndNumbersA"
    "CreatedByUserID" : "hiThere",
    "Title" : "Your wretched arm rash",
    "Comment" : "This is some good stuff"
}
```

You might have metadata in the metadata database like:

```
RecordMetaData {
    "AssociatedProblemID" : "NUMBERSANDLETTERS"
    "RecordID" : "LettersAndNumbersA",
    "DateLastModified" : "Some date"
}
```

Then you fetch the metadata by problemID and use Date last modified to see if you need to pull any changes to record "RecordID" based on comparing date modified to the one you have in the offline database.

**Comment by modelarious** [comment]
You can use the same process in reverse to upload more recent changes from offline database to online one.

**Comment by modelarious** [comment]
The case that concerns me is when someone online adds a patient record to a problem, and someone offline deletes that problem.  Offline, all the associated patient records and records will be erased along with the problem, but this process will not catch the newly created online one.

**Comment by modelarious** [comment]
For the metadata database, it doesn't need to exist, we can keep the date last modified in the patient record object if desired, I'm wondering if there is a way to only return one field from a patient record with elastic search (ie only return UserIDs or date).  I'll look into this.

**Comment by modelarious** [comment]
https://stackoverflow.com/a/9605566/7520564 says we can return only certain fields, so the date last modified metadata could just directly be stored in the Record and Patient Record object and we don't need metadata database.

**Comment by modelarious** [comment]
Don't need it for online for sure (elastic search providers this) but we should benchmark it for offline, see how much faster it is to load and inspect 5000 entries of metadata vs 5000 patient records

**Comment by modelarious** [comment]
Should we leave sync to part 5? Use only one database for everything for part 4?

**Comment by modelarious** [comment]
I agree with those steps so far, they're a good start

**Comment by tnguyen10** [comment]
Yes, I think syncing should be for part 5. For now I think we should just use elastic search
