### ISSUE TITLE
Can a User Change their User ID?

### ISSUE THREAD

**Issue by modelarious** [CMPUT301F18T20/MedicalPhotoRecord#150]
If yes, then it shouldn't be the database key.  If no, then the design is fine as is.

**Comment by deasisrj1** [comment]
I dont think the user should be able to change their userid.
it does not say anything about editing user id in the user stories
however we might need a user name 

US 03.03.01
As a patient or care provider, I want to, whenever a username is shown, be able to retrieve and see its corresponding contact information.

**Comment by kerryli33** [comment]
There wasn't anything in the specs that said we needed to be able to change user id so we should be good

**Comment by modelarious** [comment]
Sounds good, the edit user view should be changed to reflect this then.  #96 will be responsible for this change then.

**Comment by tnguyen10** [comment]
yup, I'll change that as soon as possible
