### ISSUE TITLE
What queries do we need?

### ISSUE THREAD

**Issue by modelarious** [CMPUT301F18T20/MedicalPhotoRecord#166]
Could we enumerate them all here? 

I'll start:

get all Patients for login
get all Providers for login
find Patient by UserID
find Provider by UserID
find all Problems created by a specific user id
find keywords in all fields of a Problem
find all Records created for a specific problem id (*** we can't do this yet, don't have problem id or a way to model it without the provider directly accessing the patient's problem)
find keywords in all fields of a Record
find all Patient Records created for a specific problem id (*** we can't do this yet, don't have problem id or a way to model it without the provider directly accessing the patient's problem)
find keywords in all fields of a Patient Record

find records by geo
find problems by geo??? (is this one?)
find records by body location
find problems by body location?? (is this one?)

any others?

**Comment by modelarious** [comment]
There's going to be some for photos, but those will come after next lab

**Comment by tnguyen10** [comment]
> Could we enumerate them all here?
> 
> I'll start:
> 
> get all Patients for login   (browseUserController.getPatientList) -> gets from both offline and online no syncing yet
> get all Providers for login (browseUserController.getProviderList) -> gets from both offline and online no syncing yet
> find list of patients of specific provider (browseUserController.getPatientListOfProvider) -> gets from both offline and online no syncing yet
> find Patient by UserID (modifyUserController.getPatient)
> find Provider by UserID (modifyProviderController.getProvider)
> find all Problems created by a specific user id (browseUserProblemsController.getProblemList)
> find keywords in all fields of a Problem
> find all Records created for a specific problem id (*** we can't do this yet, don't have problem id or a way to model it without the provider directly accessing the patient's problem)
> find keywords in all fields of a Record
> find all Patient Records created for a specific problem id (*** we can't do this yet, don't have problem id or a way to model it without the provider directly accessing the patient's problem)
> find keywords in all fields of a Patient Record
> 
> find records by geo
> find problems by geo??? (is this one?)
> find records by body location
> find problems by body location?? (is this one?)
> 
> any others?

modify Provider with userid, email, phone (modifyProviderController.saveProvider)
modify Patient with patient object (modifyUserController.savePatient)
add problem to patient (AddProblemController.saveProblem)
