### ISSUE TITLE
Elasticsearch UML

### ISSUE THREAD

**Issue by modelarious** [CMPUT301F18T20/MedicalPhotoRecord#17]
We must store things in elastic search for this assignment.  We have all seen in the lab the example of storing all data and retrieving all data.  Someone needs to add these triggers to the assignment that would cause a new thread to be created, and that thread to add data to the elastic search database  We also need triggers to make it fetch all the data from the elastic search server as well.

Once it has been figured out, it needs to be added to the UML available on the Michael-Committable branch (or maybe the Master branch) in the doc/ folder openable with https://www.draw.io/ and the change pushed to their branch. Pull request to merge your branch to the master branch and assign everybody to the change to let everyone see.

**Comment by tnguyen10** [comment]
did this but not sure if it's enough. need to actually set up elastic search to see.
