### ISSUE TITLE
Can you guys see the key in my pull request

### ISSUE THREAD

**Issue by Akazfu** [CMPUT301F18T20/MedicalPhotoRecord#191]
![annotation 2018-11-20 151947](https://user-images.githubusercontent.com/37144515/48806602-125d5e00-ecd8-11e8-8762-bd7a77dde288.jpg)
Looks like the API key doesn't show up in pull request, idk why.
Can anyone test if it is there, and just hidden in pll request .
should display this key in "YOUR KEY HERE"
![key](https://user-images.githubusercontent.com/37144515/48806719-7a13a900-ecd8-11e8-917b-90805679abb4.jpg)

**Comment by modelarious** [comment]
is it being ignored in any .gitignore?

**Comment by modelarious** [comment]
This was related to #189 which has been merged.
