### ISSUE TITLE
Storing bodylocation

### ISSUE THREAD

**Issue by kerryli33** [CMPUT301F18T20/MedicalPhotoRecord#226]
Currently I obtain the imageview of the part of the body that the user selects. However, I need to pass the new, updated imageview that has the "X" that the user draws on the specified area. Passing through intent is not a good idea as the bitmap may be pretty large and it is suggested not to pass large files through intent. Would it be a better idea to store it in the ElasticSearch database and retrieve it in the AddRecordsActivity or store it locally and retrieve it locally?

**Comment by modelarious** [comment]
It would be better to store and retrieve locally, just make sure to clean it up if the user decides not to create the patient record after all.

Eventually this will have to be a cache.  Right after Login (or authentication by token) we download copies of all the photos associated with the user so we can access them quickly from device storage.

**Comment by tnguyen10** [comment]
Yeah I think this should be similar to how photo is store, you should have a body location class that stores all necessary info
