### ISSUE TITLE
photo elasticsearch

### ISSUE THREAD

**Issue by modelarious** [CMPUT301F18T20/MedicalPhotoRecord#228]
Create the photo elasticsearch and make a way to fetch the photos associated with a patient record by UUID.

Photos should likely have a Bitmap for display, a label and a STRING UUID (look at how User has it) as well as a getUUID method.

Elasticsearch will need a getPhotosByPatientRecordUUID(), deletePhotoByPhotoUUID(), addPhoto(), fetchAllPhotosForPatientUserID()

a lot of which can be gotten by looking at how Patient and Problem are stored in elasticsearch.

**Comment by tnguyen10** [comment]
I updated the photo class, if you could store them as object in elastic search that would be great?

**Comment by modelarious** [comment]
I believe this is finished
