### ISSUE TITLE
How can we track that an offline problem/record/patientRecord has been deleted?

### ISSUE THREAD

**Issue by modelarious** [CMPUT301F18T20/MedicalPhotoRecord#252]
When we come online, we will need to sync deletions that happened offline.  Unless we decide right now to trash deletion of objects that don't specifically require it in the original specs.

We need to know how to tell the elasticsearch database to delete the items we deleted offline.

**Comment by modelarious** [comment]
blocking #247 #249 #250 #251

**Comment by tnguyen10** [comment]
if we want to keep it simple we could have files of deleted problems, deleted records that we keep. We can use those files to check which problem/ record to delete from elastic search once wifi is on. We then clear those file after all changes are updated to elastic search

**Comment by modelarious** [comment]
That makes sense to me.  So we have, for example, a separate file that stores all of the problems that we deleted when we're offline, and once we go online, we pass the IDs of those problems to the elasticsearch database and get rid of them.

**Comment by modelarious** [comment]
If anyone needs clarification, re-open this issue and post it in the slack
