### ISSUE TITLE
Where should we put add photo button (for record) Discussion?

### ISSUE THREAD

**Issue by tnguyen10** [CMPUT301F18T20/MedicalPhotoRecord#265]
In the add record activity and modify record activity or view record activity?

**Comment by modelarious** [comment]
I think in the add record and the modify record but not the view record

**Comment by tnguyen10** [comment]
but the problem with that would be the photo won't have record uuid, (it'll be created before the record is created) since add photo button is in the add record activity
Kerry suggests that after we save the record, we could launch the add photo activity. I think it's a good idea, what do you guys think?

**Comment by modelarious** [comment]
UUID is created on Patient Record creation.  Couldn't we just make a blank constructor and a Patient Record that belongs to the activity?

```
class AddPatientRecordActivity {
    
    //init patient record object, which inits UUID for this PatientRecord object
    PatientRecord patientRecord = new PatientRecord();

    ...

    //in onCreate we populate whatever we know about it, like the created by user ID
    public void onCreate(...) {

        ...
        this.patientRecord.setCreatedByUserID( UserIDPassedInByIntent );

        ...
    }
    ...

    //when we go to add a photo, the patientRecord has a UUID you can assign to the photo.
    public void addPhoto() {
        Photo photo = new Photo(..., this.patientRecord.getUUID());

        ...
    }
}
        
```

**Comment by tnguyen10** [comment]
But the thing is that the record should not be created during addPatientRecordActivity, it should be created when user click save. If we create the record before the user hit save, it won't be consistent.

**Comment by modelarious** [comment]
I updated the code sample to show how you would go about changing activity while maintaining the same object being edited. In summary, the object is edited by multiple activities and stored in a file specifically designated only for it. Once the user decides to commit their changes, then the object is committed to Elastic search and local storage database
