### ISSUE TITLE
About store geo to record

### ISSUE THREAD

**Issue by Akazfu** [CMPUT301F18T20/MedicalPhotoRecord#286]
@modelarious 
I actually come up a simpler way to store geo, I used intent back to addrecordactivity from geoactivity by Onclicksavebutton, and putextra longitude, latitude, and address which are preset with the values(NaN, NaN, null). and we can update the value for every time we reverse back to addrecordactivity by getextra.
Moreover, I can set up the geopoint now, It should be more convenient for you to do elastic search query.

For store geopoint and address name to record, I think I just need to modify the methods of 

AddDeleteRecordController().createRecord(this.problemUUID, this.userId, this.record_title, this.record_date, this.record_description);

Right? Tell me if I need to touch anything else.

So geo is now a part of the record.

**Comment by modelarious** [comment]
doing the "startActivityForResult" is another good way to accomplish the same thing as long as it is handled properly in the addRecordActivity.

As for updating AddDeleteRecordController, I believe that was @tnguyen10 who wrote that, so you should speak with her.  However, what you propose sounds right.

**Comment by modelarious** [comment]
and just so we are clear, all of this discussion pertains to a PATIENT record, correct?

**Comment by tnguyen10** [comment]
Kerry was the one who did all the record functionality, but I think it's fine if you modify it right now. If you're modifying add record activity, you might need to talk to @kerryli33. As @modelarious said, you should put all the geolocation stuff in patient record class instead of record class
