### ISSUE TITLE
User, Provider and Patient should throw an exception in their constructors about invalidUserID

### ISSUE THREAD

**Issue by modelarious** [CMPUT301F18T20/MedicalPhotoRecord#60]
Currently we have this:    
```
public User(String Userid, String email, String phoneNumber) {
        this.UserID = Userid;
        this.email = email;
        this.phoneNumber = phoneNumber;
}

public User(String UserID) {
        try {
                this.setUserID(UserID);
        } catch (NonNumericUserIDException e) {
            //TODO: Handle exception
        }
}
```
We need this:
```
public User(String Userid, String email, String phoneNumber) throws NonNumericUserIDException {
        this.setUserID(Userid);
        this.email = email;
        this.phoneNumber = phoneNumber;
}

public User(String UserID) throws NonNumericUserIDException {
        this.setUserID(UserID);
}
```

It seems small, but then you have to go change the test cases that use these constructors. As well as fix how the constructors in Patient and Provider class are calling the super and handle exceptions in all their test cases.

**Comment by modelarious** [comment]
@tnguyen10  just figured you'd want to see this, so I assigned you, but you can unassign yourself if you want.

**Comment by tnguyen10** [comment]
Is it possible to just use User(String Userid, String email, String phoneNumber) as our only constructor? (the other could be written as User("userid","","")), since java doesn't inherit constructors.

I'm not sure what you mean by changing test case that uses the new throws NonNumericUserIdException constructor? I could write a test case (in user unit tests) that checks if the constructor works properly. This would ensure the 'safety' of test cases in patients and provider unit test (since I'm actually passing numeric value as userId)

**Comment by modelarious** [comment]
We can do that if you'd like, doesn't affect me too much.

I mean that when your constructor now throws an exception, you have to have a try {} catch{} block everywhere that you initialize it.  So any test that didn't account for that has to be changed.  I suppose give the tests a run before committing and see if there are any compilation errors in the build.

Additionally if you want to see how you're doing with your unit testing, try "run 'app' with coverage" a few beside the play button. It will let you know which lines you have and haven't covered with testing.

**Comment by tnguyen10** [comment]
Yeah that seems very messy, it's great if Patient and Provider are not heavily use class but they are. I changed it so that constructor only takes in email and phone number, and set user id separately using setter. Is that implementation ok?

**Comment by modelarious** [comment]
That also works for me, as long as there are tests for when the exception should be triggered and ones where it shouldn't (testing valid input and making sure no exception is produced, testing invalid input and making sure the exception IS produced).  Keep in mind that there may be a restriction in the future where we need all userIDs assigned to User objects (and subclasses) to be unique.

**Comment by tnguyen10** [comment]
is it possible for us to put the restriction in the controller, so that it will keep asking user or the system for unique/ numerically id until it gets one. Instead of having it as an exception?
