### ISSUE TITLE
What would MVC look like for our project?

### ISSUE THREAD

**Issue by modelarious** [CMPUT301F18T20/MedicalPhotoRecord#70]
https://eclass.srv.ualberta.ca/pluginfile.php/4548717/mod_resource/content/2/03-MVC-Android-PartI.4up.pdf

Open discussion:

What objects in our model would extend the observable class?  Should it be our highest level objects like User and Entry?

Seems like the Boundary (View) classes should implement observer interface and contain a reference to some UI element that it's in charge of updating.  ex: One in charge of text on a button might have a button object and have the method "setButton()".  It will have "update()" that will grab data from the model and set the text on the button to that data. (please correct me if I have this wrong)

We should solidify how we will apply MVC now that we have the basics of a model to work with.

**Comment by Akazfu** [comment]
I think the activities in android are general views. 
 "implement observer interface" should be something consider when use swing imported from javax right?
