### ISSUE TITLE
Modify user

### ISSUE THREAD

**Issue by tnguyen10** [CMPUT301F18T20/MedicalPhotoRecord#96]

**Comment by tnguyen10** [comment]
done for offline, need to do elastic search, controller and ui test

**Comment by modelarious** [comment]
This needs to address Issue #150 by making it so UserIDs cannot be changed.  It's been decided that changing UserID complicates the design unnecessarily. @tnguyen10

**Comment by tnguyen10** [comment]
ok cool I'll fix it asap

**Comment by tnguyen10** [comment]
TODO:  UI test

**Comment by tnguyen10** [comment]
TODOs: elasticSearch delete patient

**Comment by modelarious** [comment]
there's a simple ui test that covers this in pull request #193, in PatientHomeMenuActivityTest.java called EditingAUserMaintainsChangesWhileOnline.  It pulls up a user account, changes their phone number and email, saves changes, presses back and then views their user account to see if the changes took.  You could use this to help your development if you'd like.

**Comment by tnguyen10** [comment]
cool, I think I'll use your elastic search SaveModifiedPatient to modify user, then test it in similar way as EditingAUserMaintainsChangesWhileOnline
