### ISSUE TITLE
Browse user (patients), problems, records

### ISSUE THREAD

**Issue by tnguyen10** [CMPUT301F18T20/MedicalPhotoRecord#97]

**Comment by tnguyen10** [comment]
doing browser patient's activity now

**Comment by modelarious** [comment]
Does this cover all three of the browse activities?

**Comment by tnguyen10** [comment]
yes, some one could take the other browse records and browse problems if they want. Please let me know

**Comment by tnguyen10** [comment]
browse user and browse problems are done for offline

**Comment by tnguyen10** [comment]
need to do elastic search, controller and ui test

**Comment by tnguyen10** [comment]
browse user elastic search done, but needs to check syncing

**Comment by tnguyen10** [comment]
TODO: elastic search, UI Test

**Comment by tnguyen10** [comment]
doing browse records now
